- name: Managed ssh authorized_keys
  authorized_key:
    user: "{{ item.user }}"
    key: "{{ item.key }}"
    key_options: "{{ item.key_options | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    exclusive: "{{ item.exclusive | default(omit) }}"
    manage_dir: "{{ item.manage_dir | default(omit) }}"
    path: "{{ item.path | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    validate_certs: "{{ item.validate_certs | default(omit) }}"
  loop: "{{ authorized_keys }}"
  tags:
    - ssh
    - authorized_keys
    - ssh_keys
